language: r
r:
  - oldrel
  - release
  - devel

pandoc_version: 2.0.3

cache: packages

# Be strict when checking our package
warnings_are_errors: true

# Suggested packages needed to run tests
r_packages:
  - car
  - afex
  - lsmeans
  - multcomp
  - MBESS
  - ggplot2
  - dplyr
  - downloader
  - testthat
  - BayesFactor
  - latex2exp

# Install other dependencies # longtable lscape tabularx
before_install:
  - tlmgr install apa6 was threeparttablex endfloat substr lineno

addons:
 apt:
   packages:
   - lmodern
   - libgsl0ldbl # GNU scientific library for MBESS
   - libgsl0-dev # GNU scientific library for MBESS
   - libnlopt-dev # nloptr
