language: r
r:
  - oldrel
  - release
  - devel

# Be strict when checking our package
warnings_are_errors: true

# Suggested packages needed to run tests
r_packages:
  - testthat
  - afex

# Install GNU Scientific library for MBESS
before-install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgsl0ldbl
