language: r
r:
  - oldrel
  - release
  - devel

cache: packages

# Be strict when checking our package
warnings_are_errors: true

# Suggested packages needed to run tests
r_packages:
  - testthat
  - afex
  - MBESS

# Install other dependencies # longtable lscape tabularx
before_install:
  - tlmgr install apa6 was threeparttablex endfloat substr lineno

addons:
 apt:
   packages:
   - lmodern
   - libgsl0ldbl # GNU scientific library for MBESS
   - libgsl0-dev # GNU scientific library for MBESS
